### ISSUE TITLE
Docker compose difficulties

### ISSUE THREAD

**Issue by samudurand** [ches/docker-kafka#29]
Hi Ches , I saw an issue in which you mentioned you were going to add an example of docker-compose a year ago, do you have it ? I am myself trying to create a file for that but kafka does not seem able to see zookeeper, while it works properly when running with `docker run` and --link.

Here is my file : 

```
version: '2'
services:

  kafka:
    container_name: kafka
    image: ches/kafka:0.10.1.0
    depends_on:
      - zookeeper

  zookeeper:
    container_name: zookeeper
    image: jplock/zookeeper:3.4.6
```

I am getting errors like 

```
kafka        | [2016-12-07 09:29:01,391] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
kafka        | [2016-12-07 09:29:01,392] WARN Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
kafka        | java.net.ConnectException: Connection refused
kafka        | 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
kafka        | 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
kafka        | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
kafka        | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
```
