### ISSUE TITLE
Dodcumentation on how to set up docker-compose.yml?

### ISSUE THREAD

**Issue by iand675** [ches/docker-kafka#44]
Sorry for seeking tech support, but I've looked around fairly extensively on how to this image up via docker compose, and haven't had much luck. Would you be able to add documentation to the README detailing a working setup with compose?

Here's my non-working configuration at the moment.

``` yaml
version: "2"

services:
  kafka:
    hostname: localhost
    image: ches/kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - ZOOKEEPER_IP=127.0.0.1
    links:
      - zookeeper
    ports:
      - "9092:9092"
      - "7203:7203"
  zookeeper:
    hostname: localhost
    image: zookeeper
    ports:
      - "2181:2181"
```

**Comment by ches** [comment]
Hi,

No problem, I've been meaning to add Docker Compose examples for ages, in fact I have some sitting around in my local working copy that I just need to polish up and push. In the meantime this ought to be pretty close:

```yaml
version: '3'

services:
  kafka:
    image: ches/kafka
    depends_on:
      - zookeeper
    environment:
      # Use container hostname support of the default Compose network
      ZOOKEEPER_IP: zookeeper
    ports:
      - '9092:9092'  # Kafka broker
      - '7203:7203'  # JMX
    volumes:
      - kafka-data:/data
      - kafka-logs:/logs

  zookeeper:
    image: zookeeper:3.4
    restart: unless-stopped
    ports:
      - '2181:2181'

volumes:
  kafka-data:
  kafka-logs:
```

This is probably compatible with the v2 file format also, I haven't tested.

If this doesn't work, can you let me know more details about the problems you have for your use case? There can be some troublesome bits with mapped ports for Kafka using Docker on Mac or Windows, where there is technically still a VM running the Docker daemon under the covers but they try to magically abstract the mapping of ports to your localhost. It Just Works most of the time but Kafka in particular has some complications with it, related to advertised host name.

All of that basically disappears if you can do everything within the Docker network and not map ports, but that certainly limits convenience for local development.
