### ISSUE TITLE
zookeeper.connect issue on 0.9.0.1 image

### ISSUE THREAD

**Issue by andremleblanc** [ches/docker-kafka#46]
Hey, thanks for your work on these build descriptions.
 
I think I may have found a bug with with 0.9.0.1 image on Docker Hub. 

This is an excerpt from the docker-compose file I was writing.
```
services:
  zookeeper:
    image: zookeeper:3.4
    hostname: localhost
    networks:
      - druiddb-docker
    ports:
      - '2181:2181'

  kafka:
    image: ches/kafka:0.9.0.1
    hostname: localhost
    networks:
      - druiddb-docker
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_IP=zookeeper
```

This will return the below error:
```
kafka_1      | org.apache.kafka.common.config.ConfigException: Missing required configuration "zookeeper.connect" which has no default value.
```

Changing the kafka version fixes the issue.
```
services:
  zookeeper:
    image: zookeeper:3.4
    hostname: localhost
    networks:
      - druiddb-docker
    ports:
      - '2181:2181'

  kafka:
    image: ches/kafka:0.10.2.1
    hostname: localhost
    networks:
      - druiddb-docker
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_IP=zookeeper
```
I tried a few different things to get my build to work with the `0.9.0.1` version, but had no luck. Using the newer version of Kafka is fine for me, but thought I would point it out.
