### ISSUE TITLE
How to add docker-compose

### ISSUE THREAD

**Issue by hieutrtr** [ches/docker-kafka#5]
Hi Ches,
 I have just pulled docker-kafka source and then add docker-compose.yml like this:

```
zookeeper:
  image: jplock/zookeeper:3.4.6
kafka:
  build: .
  links:
    - zookeeper
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
```

So, I cant get why the kafka doesnt work when i run "docker-compose up".

zookeeper is still start like normal, but the kafka just work when i use image: ches/docker-kafka instead of build . (with your source).

Hope to hear from you soon,
Thanks.
